### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by holtgrewe** [hurngchunlee/docker-irods#1]
Hi, could you provide a license for your work?

**Comment by hurngchunlee** [comment]
@holtgrewe are you planning to use this repository?  I created this repo 4 years ago when we were evaluating the iRODS data management system; therefore there is no license attached to it.  I am not sure if the work is still valid/useful; and I have no intention to maintain it.

If you find it useful for you, feel free to use it.  I just attached the MIT license to this repo.

**Comment by holtgrewe** [comment]
@hurngchunlee thanks.

Actually I've based my repo https://github.com/bihealth/irods-docker on your scripts, so I'll use my own repository but parts of your code.

**Comment by hurngchunlee** [comment]
You are welcome. Good to know that the repo is useful.
